### ISSUE TITLE
Immutable Resources - create strategy and document best practices

### ISSUE THREAD

**Issue by elf-pavlik** [solid/specification#459] opened 2022-09-29 18:00 UTC
This issue takes inspiration from #454 and aims at consistency across all specifications in Solid Ecosystem.

In [Solid Application Interoperability](https://solid.github.io/data-interoperability-panel/specification/) (aka *SAI*) we define some resources as Immutable. They are never modified and when needed are replaced with new immutable resources.

This came out of implementation experience and allows much simpler handling of various artifacts (represented by web resources) that SAI relies on. We only use it for artifacts that are specific to SAI, that is only relevant in a specific context, and clients follow their noses to them through other resources which guarantee stable URIs.

I'm going to document our experience from writing SAI spec and implementing it. If other specs can also take advantage of immutable resources, we can collaborate on a common strategy and document best practices.

**Comment by csarven** [comment] 2022-09-29 18:14
Closing this issue because it appears to be a duplicate of an issue created in 2019: https://github.com/solid/specification/issues/279 , with title "mutable and immutable resources".

Even if off chance it is not a "duplicate" because of emphasis on "strategy and best practices", it seems more appropriate to cover it in SAI-BP - which I can only encourage you to create one - because as you say, it is specific to SAI in a specific context.

**Closed** 2022-09-29 18:14 UTC
